appName: microcks

microcks:
  url: microcks-microcks.192.168.99.100.nip.io
  #url: microcks-microcks.192.168.64.6.nip.io
  #ingressSecretRef: my-secret-for-microcks-ingress
  #ingressAnnotations:
    #cert-manager.io/issuer: my-cert-issuer
    #kubernetes.io/tls-acme: "true"
    #kubernetes.io/ingress.class: nginx
  generateCert: true
  image: quay.io/microcks/microcks:1.1.0
  replicas: 1
  
postman:
  image: quay.io/microcks/microcks-postman-runtime:latest
  replicas: 1

keycloak:
  install: true
  realm: microcks
  url: keycloak-microcks.192.168.99.100.nip.io
  #privateUrl: http://microcks-keycloak.microcks.svc.cluster.local:8080/auth
  #ingressSecretRef: my-secret-for-keycloak-ingress
  #ingressAnnotations:
    #cert-manager.io/issuer: my-cert-issuer
    #kubernetes.io/tls-acme: "true"
    #kubernetes.io/ingress.class: nginx
  generateCert: true
  image: jboss/keycloak:10.0.1
  adminUsername: admin
  # Unless you uncomment following line, admin password will be randomly generated.
  # Beware that in case of update, new value will be generated and
  #adminPassword: 123

  persistent: true
  volumeSize: 1Gi
  postgresImage: centos/postgresql-95-centos7:latest
  username: userP
  # Unless you uncomment following line, admin password will be randoMly generated.
  # Beware that in case of update, new value will be generated and
  #password: 123

  serviceAccount: microcks-serviceaccount
  serviceAccountCredentials: ab54d329-e435-41ae-a900-ec6b3fe15c54

mongodb:
  install: true
  #uri: mongodb:27017
  #database: sampledb
  image: centos/mongodb-34-centos7:latest
  persistent: true
  volumeSize: 2Gi
  
  username: userM
  # Unless you uncomment following line, admin password will be randomly generated.
  # Beware that in case of update, new value will be generated and overwrite existing one.
  #password: 123

  # Or you can uncomment secretRef block if username and password are provided through a Secret.
  #secretRef:
    #secret: mongodb
    #usernameKey: database-user
    #passwordKey: database-password

features:
  async:
    enabled: false
    defaultBinding: KAFKA
    defaultFrequency: 10
    defaultAvroEncoding: RAW
    
    image: quay.io/microcks/microcks-async-minion:1.1.0

    kafka:
      install: true
      url: 192.168.99.100.nip.io
      #url: kafka-bootstrap:9092
      persistent: false
      volumeSize: 2Gi

      schemaRegistry:
        #url: http://schema-registry.192.168.99.100.nip.io
        confluent: true
        username: microcks
        credentialsSource: USER_INFO

    # Uncomment the mqtt.url and put a valid endpoint address below to enable MQTT support.
    mqtt:
      #url: artemis:1883
      username: microcks
      password: microcks

  repositoryFilter:
    enabled: false
    labelKey: app
    labelLabel: Application
    labelList: app,status
