{{- if and .Values.mongodb.install .Values.mongodb.persistent }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-mongodb"
  labels:
    app: "{{ .Values.appName }}"
    container: mongodb
    group: microcks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.volumeSize }}
{{- end }}
{{- if and .Values.keycloak.install .Values.keycloak.persistent }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-keycloak-postgresql"
  labels:
    app: "{{ .Values.appName }}"
    container: keycloak-postgresql
    group: microcks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.keycloak.volumeSize }}
{{- end }}