{{- if and .Values.features.async.enabled .Values.features.async.kafka.install }}
kind: Kafka
apiVersion: kafka.strimzi.io/v1beta1
metadata:
  name: "{{ .Values.appName }}-kafka"
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      log.message.format.version: "2.5"
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
      plain: {}
      tls: {}
      external:
        type: ingress
        configuration:
          bootstrap:
            host: "{{ .Values.appName }}-kafka.{{ .Values.features.async.kafka.url }}"
          brokers:
          - broker: 0
            host: "{{ .Values.appName }}-kafka-0.{{ .Values.features.async.kafka.url }}"
    replicas: 1
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
{{- end }}