{{- if and (not .Values.microcks.ingressSecretRef) (.Values.microcks.generateCert) }}
---
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-microcks-ingress-secret"
  labels:
    app: "{{ .Values.appName }}"
    group: microcks
type: kubernetes.io/tls
data:
{{ ( include "microcks-ingress.gen-certs" . ) | indent 2 }}
{{- end }}
{{- if .Values.keycloak.install }}
{{- if and (not .Values.keycloak.ingressSecretRef) (.Values.keycloak.generateCert) }}
---
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-keycloak-ingress-secret"
  labels:
    app: "{{ .Values.appName }}"
    group: microcks
type: kubernetes.io/tls
data:
{{ ( include "keycloak-ingress.gen-certs" . ) | indent 2 }}
{{- end }}
---
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-certificates"
  labels:
    app: "{{ .Values.appName }}"
    container: mongodb
    group: microcks
#type: kubernetes.io/tls
data:
  truststore.p12: {{ .Values.microcks.truststore }}
---
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-keycloak-admin"
  labels:
    app: "{{ .Values.appName }}"
    container: keycloak
    group: microcks
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.keycloak.adminUsername }}"
  postgresUsername: "{{ .Values.keycloak.username }}"
data:
  {{- if .Values.keycloak.adminPassword }}
  password: {{ .Values.keycloak.adminPassword | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
  {{- if .Values.keycloak.password }}
  postgresPassword: {{ .Values.keycloak.password | b64enc | quote }}
  {{- else }}
  postgresPassword: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.keycloak.database }}
  postgresDatabase: {{ .Values.keycloak.database | b64enc | quote }}
  {{- else }}
  postgresDatabase: root
  {{- end }}
  {{- if .Values.keycloak.dburl }}
  postgresUrl: {{ .Values.keycloak.dburl | b64enc | quote }}
  {{- else }}
  postgresUrl: "{{ .Values.appName }}-keycloak-postgresql"
  {{- end }}
  {{- if .Values.keycloak.jdbcparams }}
  postgresJDBCParams: {{ .Values.keycloak.jdbcparams | b64enc | quote }}
  {{- else }}
  postgresJDBCParams: ""
  {{- end }}
{{- end }}