kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-certificates"
  labels:
    app: "{{ .Values.appName }}"
    container: mongodb
    group: microcks
#type: kubernetes.io/tls
data:
  truststore.p12: {{ .Values.microcks.truststore }}
{{- if and (not .Values.microcks.ingressSecretRef) (.Values.microcks.generateCert) }}
---
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-microcks-ingress-secret"
  labels:
    app: "{{ .Values.appName }}"
    group: microcks
type: kubernetes.io/tls
data:
{{ ( include "microcks-ingress.gen-certs" . ) | indent 2 }}
{{- end }}
